### ISSUE TITLE
MQTT entities have an entity name that starts with the device name

### ISSUE THREAD

**Issue by mushuthecat** [adorobis/speedtest-CLI2mqtt#5]
Hi,

Just for your information since the last release we have this warning :

```
Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

    sensor.speedtest_net_ping
    sensor.speedtest_net_upload
    sensor.speedtest_net_server
    sensor.speedtest_net_isp
    binary_sensor.speedtest_net_status
    sensor.speedtest_net_download
```

![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/83928911/7dbfd9c8-200d-4ff1-939b-5466119ed134)

Thanks

**Comment by adorobis** [comment]
Thanks for raising this. 
For now you can ignore it, I'll fix it in the next two weeks.

**Comment by adorobis** [comment]
Fixed here https://github.com/adorobis/speedtest-CLI2mqtt/pull/6

**Comment by adorobis** [comment]
Code fixed, I'll update the docker images in next 2 weeks

**Comment by adorobis** [comment]
Docker images updated as well now

**Comment by mushuthecat** [comment]
Hello,

I just performed an update of my docker image and still have the same
warning from the ha dashboard

**Comment by adorobis** [comment]
hm, strange. I've just checked on my install and the MQTT messages are correctly updated after pulling the latest image. It all looks ok in HA. Could you make sure that you have pulled the latest docker image e.g. adorobis/speedtest2mqtt:latest ? If yes, could you check the MQTT messages e.g. with MQTTExplorer, the `homeassistant/sensor/speedtest_net_download/config` should look like below:
```
{"name": "Download", "has_entity_name": true, "availability_topic": "speedtest/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtest-speedtest_net_download", "device": {"identifiers": ["speedtest"], "name": "Speedtest.net", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtest/download", "unit_of_measurement": "Mbit/s", "state_class": "measurement"}
```
The beginning should be:
`"name": "Download", "has_entity_name": true`

**Comment by mushuthecat** [comment]
Hi @adorobis 

My docker-compose.yaml contains and i performed a docker-compose pull and docker-compose up -d 
```
version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: adorobis/speedtest2mqtt:latest
    restart: always
    volumes:
      - ./config:/usr/src/config

```


This is the result of my MQTTT message:
![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/83928911/c9b36607-a15e-48c0-901a-b7a6593a89ac)

**Comment by adorobis** [comment]
So everything looks good, just restart ha now
